#:schema node_modules/wrangler/config-schema.json
name = "story-audience-dev"
compatibility_date = "2024-12-11"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".svelte-kit/cloudflare"